#!/usr/bin/env python3
"""
Write README.md index files under src/questions/: each folder lists direct
problem .md files (links point to built .html for GitHub Pages / Jekyll) and
links to subfolders' README.html. Regenerate after adding or renaming problems.

README.md is on the jekyll-optional-front-matter blacklist; each index file
includes YAML front matter so Jekyll still renders it.

Usage: python scripts/generate_question_indexes.py
"""

from __future__ import annotations

import os
from pathlib import Path
from urllib.parse import quote

REPO_ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_ROOT = REPO_ROOT / "src" / "questions"
INDEX_NAME = "README.md"
INDEX_HTML = "README.html"

FRONT_MATTER = """---
layout: default
---
"""

# Friendly titles for top-level topic folders (fallback: hyphen -> space, title case)
TOP_LEVEL_TITLES: dict[str, str] = {
    "arrays": "Arrays",
    "binary-search": "Binary search",
    "cpp-stl": "C++ STL",
    "cses": "CSES",
    "data-structure-implementations": "Data structure implementations",
    "dp": "Dynamic programming",
    "dsu": "Disjoint set union (DSU)",
    "fenwick-and-segment-trees": "Fenwick & segment trees",
    "graphs": "Graphs",
    "heaps": "Heaps",
    "linked-list": "Linked list",
    "math": "Math",
    "misc": "Misc",
    "queue": "Queue",
    "recursion-and-backtracking": "Recursion & backtracking",
    "sliding-window": "Sliding window",
    "stack": "Stack",
    "subarray-hashing": "Subarray hashing",
    "trees": "Trees",
    "usaco": "USACO",
}


def folder_heading(name: str, rel: Path) -> str:
    if not rel.parts:
        return "All topics"
    parts = rel.parts
    if len(parts) == 1 and parts[0] in TOP_LEVEL_TITLES:
        return TOP_LEVEL_TITLES[parts[0]]
    if name == "DP":
        return "DP"
    if name == "Trees":
        return "Trees"
    return name.replace("-", " ").replace("_", " ").title()


def linkify_filename(name: str) -> str:
    """Relative URL after Jekyll build: .md sources become .html on GitHub Pages."""
    if name.lower().endswith(".md"):
        base = name[: -len(".md")]
        return "./" + quote(base, safe="") + ".html"
    return "./" + quote(name, safe="")


def title_from_md(name: str) -> str:
    base = name[: -len(".md")] if name.lower().endswith(".md") else name
    return base


def navigation(readme_path: Path) -> str:
    rel = readme_path.relative_to(QUESTIONS_ROOT)
    if rel == Path(INDEX_NAME):
        return "[← Repository overview](../../)\n\n"
    return "[← Parent](../README.html)\n\n"


def should_skip_dir(name: str) -> bool:
    return name.startswith(".") or name in ("__pycache__",)


def collect_dirs(root: Path) -> list[Path]:
    out: list[Path] = []
    for dirpath, dirnames, _ in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if not should_skip_dir(d))
        out.append(Path(dirpath))
    return sorted(out, key=lambda p: str(p).lower())


def write_index_for_dir(folder: Path) -> bool:
    md_files = sorted(
        f
        for f in os.listdir(folder)
        if f.lower().endswith(".md") and f != INDEX_NAME
    )
    subdirs = sorted(
        d for d in os.listdir(folder) if (folder / d).is_dir() and not should_skip_dir(d)
    )

    if not md_files and not subdirs:
        return False

    readme_path = folder / INDEX_NAME
    rel = folder.relative_to(QUESTIONS_ROOT)
    heading = folder_heading(folder.name, rel)

    lines: list[str] = [
        FRONT_MATTER.rstrip(),
        "",
        f"# {heading}",
        "",
        "<!-- Generated by scripts/generate_question_indexes.py; do not edit by hand. -->",
        "",
        navigation(readme_path),
    ]

    if md_files:
        lines.append("## Problems")
        lines.append("")
        for f in md_files:
            label = title_from_md(f)
            lines.append(f"- [{label}]({linkify_filename(f)})")
        lines.append("")

    if subdirs:
        lines.append("## Subfolders")
        lines.append("")
        for sd in subdirs:
            label = folder_heading(sd, rel / sd)
            lines.append(f"- [{label}](./{sd}/{INDEX_HTML})")
        lines.append("")

    text = "\n".join(lines).rstrip() + "\n"
    readme_path.write_text(text, encoding="utf-8")
    return True


def main() -> None:
    if not QUESTIONS_ROOT.is_dir():
        raise SystemExit(f"Missing questions root: {QUESTIONS_ROOT}")

    written = 0
    for folder in collect_dirs(QUESTIONS_ROOT):
        if write_index_for_dir(folder):
            written += 1

    print(f"Wrote {written} {INDEX_NAME} file(s) under {QUESTIONS_ROOT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
